# Generated by Django 5.2.17 on 2026-10-07 16:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_businessprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('item_code', models.CharField(blank=True, help_text='Your own code for this item. Leave blank if not used.', max_length=50, verbose_name='Item code / SKU')),
                ('barcode', models.CharField(blank=True, help_text='EAN / UPC barcode. Leave blank if not used.', max_length=50)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], db_index=True, default='PRODUCT', help_text='Products carry stock. Services do not.', max_length=8)),
                ('hsn_sac_code', models.CharField(blank=True, help_text='4, 6 or 8 digits. Goods use HSN, services use SAC.', max_length=8, verbose_name='HSN / SAC code')),
                ('service_description', models.CharField(blank=True, help_text='Required for services: the description printed on the tax invoice.', max_length=80)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('NOS', 'Numbers'), ('KG', 'Kilogram'), ('GM', 'Gram'), ('LTR', 'Litre'), ('ML', 'Millilitre'), ('MTR', 'Metre'), ('CM', 'Centimetre'), ('FT', 'Foot'), ('M2', 'Square metre'), ('M3', 'Cubic metre'), ('BOX', 'Box'), ('BAG', 'Bag'), ('CBM', 'Cubic metre (CBM)'), ('DZN', 'Dozen'), ('SET', 'Set'), ('PAIR', 'Pair'), ('SQFT', 'Square foot'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('MONTH', 'Month')], default='PCS', help_text='Unit of sale, e.g. PCS, KG, LTR.', max_length=8)),
                ('sales_price', models.DecimalField(decimal_places=2, help_text='Default selling price before tax (or tax-inclusive, see below).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Default buying price. Optional.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_includes_tax', models.BooleanField(default=False, help_text='On when sales_price already contains GST, so tax is extracted from it.')),
                ('tax_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('1.50'), '1.5%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), help_text='Applicable GST rate as a percentage.', max_digits=5)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity on hand. NULL for services (not stock-tracked).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, help_text='Alert when stock falls to this level. NULL to disable the alert.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Inactive items are hidden from pickers but preserved for historic invoices.')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'item_type', 'is_active'], name='inventory_i_busines_861e89_idx'), models.Index(fields=['business', 'name'], name='inventory_i_busines_9e5710_idx'), models.Index(fields=['business', 'item_code'], name='inventory_i_busines_30142a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('item_code__gt', '')), fields=('business', 'item_code'), name='unique_item_code_per_business'), models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('business', 'barcode'), name='unique_barcode_per_business')],
            },
        ),
    ]
