# Generated by Django 5.2.17 on 2026-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_businessprofile_logo'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_code_per_business',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_barcode_per_business',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('item_code__gt', '')), fields=('business', 'item_code'), name='unique_item_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', ''), ('is_active', True)), fields=('business', 'barcode'), name='unique_barcode_per_business'),
        ),
    ]
