# Generated by Django 5.2.17 on 2026-10-08 08:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_unique_item_code_per_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('1.50'), '1.5%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12% (retired)'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28% (retired)'), (Decimal('40.00'), '40%')], decimal_places=2, default=Decimal('18.00'), help_text='Applicable GST rate as a percentage.', max_digits=5),
        ),
    ]
