# Generated by Django 5.2.17 on 2026-10-08 08:19

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional product photo. Shown on the catalogue and on invoice PDFs.', upload_to=apps.inventory.models.item_image_upload_path),
        ),
    ]
