# Generated by Django 5.2.17 on 2026-10-06 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_businessprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Both')], db_index=True, default='CUSTOMER', max_length=10)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9][0-9]{9}$', 'Enter a valid 10-digit Indian mobile number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, help_text='15-character GSTIN. Leave blank for unregistered parties.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN, e.g. 36ABCCS2942R1ZR.')], verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, help_text='10-character PAN. Auto-filled from GSTIN if provided.', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Enter a valid 10-character PAN, e.g. ABCCS2942R.')], verbose_name='PAN')),
                ('state_code', models.CharField(choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chandigarh'), ('05', 'Uttarakhand'), ('06', 'Haryana'), ('07', 'Delhi'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'Mizoram'), ('16', 'Tripura'), ('17', 'Meghalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'Odisha'), ('22', 'Chhattisgarh'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('27', 'Maharashtra'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'Lakshadweep'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'Puducherry'), ('35', 'Andaman and Nicobar Islands'), ('36', 'Telangana'), ('37', 'Andhra Pradesh'), ('38', 'Ladakh')], db_index=True, help_text='2-digit GST state code. Determines intra/inter-state taxation.', max_length=2)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_pincode', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Enter a valid 6-digit pincode.')])),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_pincode', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Enter a valid 6-digit pincode.')])),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance as of the start date. Positive number only.', max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999.99)])),
                ('balance_type', models.CharField(choices=[('CREDIT', 'Credit (Party owes us)'), ('DEBIT', 'Debit (We owe party)')], default='CREDIT', help_text='CREDIT = Party owes us (receivable). DEBIT = We owe party (payable).', max_length=6)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Inactive parties are hidden from dropdowns but preserved for historical records.')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'party_type', 'is_active'], name='parties_par_busines_0254fa_idx'), models.Index(fields=['business', 'name'], name='parties_par_busines_b86775_idx'), models.Index(fields=['business', 'gstin'], name='parties_par_busines_d580b7_idx'), models.Index(fields=['business', 'mobile'], name='parties_par_busines_2e209a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gstin__gt', '')), fields=('business', 'gstin'), name='unique_gstin_per_business'), models.UniqueConstraint(condition=models.Q(('pan__gt', '')), fields=('business', 'pan'), name='unique_pan_per_business')],
            },
        ),
    ]
