# Generated by Django 5.2.17 on 2026-10-07 14:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening balance as of the start date. Positive number only.', max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))]),
        ),
    ]
