# Generated by Django 5.2.17 on 2026-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_businessprofile_logo'),
        ('parties', '0002_alter_party_opening_balance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_gstin_per_business',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_pan_per_business',
        ),
        migrations.AddField(
            model_name='party',
            name='shipping_state_code',
            field=models.CharField(blank=True, choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chandigarh'), ('05', 'Uttarakhand'), ('06', 'Haryana'), ('07', 'Delhi'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'Mizoram'), ('16', 'Tripura'), ('17', 'Meghalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'Odisha'), ('22', 'Chhattisgarh'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('27', 'Maharashtra'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'Lakshadweep'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'Puducherry'), ('35', 'Andaman and Nicobar Islands'), ('36', 'Telangana'), ('37', 'Andhra Pradesh'), ('38', 'Ladakh')], help_text='Set only when goods are shipped to a different state from the billing address. It decides place of supply for goods on an invoice (intra-state CGST+SGST vs inter-state IGST). Leave blank to ship to the billing state.', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin__gt', ''), ('is_active', True)), fields=('business', 'gstin'), name='unique_gstin_per_business'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('pan__gt', '')), fields=('business', 'pan'), name='unique_pan_per_business'),
        ),
    ]
