# Generated by Django 5.2.17 on 2026-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile_hsn_requirement'),
        ('parties', '0003_remove_party_unique_gstin_per_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text="The business's walk-in / cash customer. At most one per business. Its place of supply is resolved from the business at invoice time."),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_walk_in', True)), fields=('business',), name='one_walk_in_per_business'),
        ),
    ]
