# Generated by Django 5.2.17 on 2026-10-06 06:42

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.logo_upload_path),
        ),
    ]
