# Generated by Django 5.2.17 on 2026-10-08 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_businessprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='gst_registration_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('COMPOSITION', 'Composition'), ('UNREGISTERED', 'Unregistered')], default='UNREGISTERED', help_text="Only 'Regular' businesses may charge GST on an invoice. Composition and Unregistered businesses must show tax as zero and use the title 'Bill of Supply'.", max_length=15),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', help_text='1-4 letters/digits used at the start of the invoice number, e.g. INV.', max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{1,4}$', 'Prefix must be 1-4 characters using A-Z, 0-9 or a hyphen (e.g. INV).')]),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='round_invoice_total',
            field=models.BooleanField(default=False, help_text="Round the invoice total to the nearest rupee and show a 'Round Off' line. Presentation only: taxable values and tax amounts never change."),
        ),
    ]
