# Generated by Django 5.2.17 on 2026-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_walk_in_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='hsn_requirement',
            field=models.CharField(choices=[('STRICT', 'Strict - every line'), ('STATUTORY', 'Statutory - above Rs 5,000 to a GSTIN holder')], default='STRICT', help_text='STRICT asks for an HSN/SAC code on every line of every tax invoice. STATUTORY only requires it above Rs 5,000 to a GSTIN holder, which is what the law actually says. STRICT over-complies on purpose - confirm with your CA before switching.', max_length=10),
        ),
    ]
