# Generated by Django 5.2.17, then documented.
#
# Decision 22 replaces decision 18's `hsn_requirement` (STRICT / STATUTORY) with
# a digit count, `hsn_min_digits` (4 or 6).
#
# Why remove the field outright instead of migrating the values across:
#
#   * The OLD `STATUTORY` mode gated on a per-invoice Rs 5,000 threshold, which
#     is not an HSN rule at all - it is an old reverse-charge daily limit. The
#     digit requirement actually depends on the business's own annual turnover.
#   * Every business now behaves like the old `STRICT`: an HSN/SAC is required on
#     every line, and only the minimum digit count varies. So a business that
#     had switched to `STATUTORY` becomes *stricter* after this migration.
#
# That direction is deliberate and safe. Under-compliance in a filed return
# cannot be undone, whereas a superfluous digit is harmless, so defaulting
# everyone to the stricter behaviour is the recoverable direction. No business
# needs its setting changed to stay compliant at 4 digits, which is the default.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile_hsn_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='hsn_requirement',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hsn_min_digits',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 digits (turnover up to Rs 5 crore)'), (6, '6 digits (turnover above Rs 5 crore)')], default=4, help_text='How many digits of the HSN/SAC code your GSTR-1 needs. 4 digits up to Rs 5 crore annual turnover, 6 digits above. Every line of every tax invoice must meet this minimum. Confirm the figure with your CA.', verbose_name='HSN/SAC digits required'),
        ),
    ]
